### ISSUE TITLE
Ok i feel like you scammed me

### ISSUE THREAD

**Issue by net1872** [Craggyiz/.io-Bots-and-Protocols#3]
dd

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Stargazerr1** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
